apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:UsLzmyClonE=,iv:dw823ik4Dc5uRwuwkhEqyB43AHtlvbjMX/WoFevP9Tg=,tag:triU2V60RiAd6NYOco2r8Q==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:eea46Y+NhjtJByU=,iv:bQ4V3FRg7nB6wbJe7UBmswAqgSMMLUNUEt3CDMncAxw=,tag:4DiaVCjmJ8GogjtiBVJBlA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:9yNwdNDsCK05fA==,iv:8KuBIoS9XMzQWxoknSCAc5A0zMiLfUaTGilVLrLRMYc=,tag:FVwOm7arkXmXQYshiyacrQ==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:gWgvtC4Xjip70gcrEAP7cXyHQuOfHMu+7JOF5z06KJ2kxh2wegKXs7lvVRelomy5olDTHlA=,iv:xlpS351ViplyRCI7c2Pcu57XSXmSUzaPJYcQqj6gsec=,tag:+9nEfLEaVvlNlVxJLA+NJA==,type:str]
  #ENC[AES256_GCM,data:RbnYtIf0PlQ6AqHT6sEX1UI+uDviX++dQnT6GDSYKoZbw2UMGTMJ3Xr6ZARH/Idb65L8xPoz2rx+2+v6uH7zVA5NFo0CSya2+JVWlw==,iv:0S04Wunj0aERpdqAEfJbq1aM44tgf2REFtffiE0UCiw=,tag:rv2+xerTSGgownaVkHm9XQ==,type:comment]
  #ENC[AES256_GCM,data:WNnDW+WgjFkJG6FlZ6UFp+XxHGGR+nMTbn/T7spm9ui0YmI5rs7lGgQ5Gu2CRmJAvOYJW6MuuGivVOGBpB6TjJOgi9DjmMVB,iv:FpiTrL/eh8QHP+shxgbcsDsp0kBBHFCE1hArJxR9RBk=,tag:bMfCIz6g7CkTB+uwlA4cGQ==,type:comment]
  #ENC[AES256_GCM,data:4MoLHmprtm3PSFbVc85F3lx7+yHy4dT7SKggTmgfTsiYL7+WyeJ8cmYXbRJFEamGGuPR/ORFPmw1SrFVZCAPaAuxljjiTONKHuJc2Q==,iv:nbWpMLQUQIROBvE8gsAf5hw3KFVMLGYOxMLxq2aq2QU=,tag:X9jCqPY1urwEARwZK4IN7g==,type:comment]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:eOByZrBd0cg3pw==,iv:rN3/yN56OOngxmGNsw9Jx6BkFFf7RIczi2Mu7i+23x0=,tag:Vw/Qwo8OmZSGQrMdfyBVYQ==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:UZFfEZBqAZJB6Q==,iv:1T/iVBSHqyO08SyQHRHocXFnzYWF9+yU4dJTqBM4rs0=,tag:zrR7z6G46B8CKrHbssqwGQ==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:EmqkJF9by3DJNA==,iv:azI3z+/irwmRDKYtXdX2gv3RHB4rMujftf6QbSwyC1w=,tag:5NrTuyVIi0bwE6GhBfcybw==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ENC[AES256_GCM,data:0OLdazsdXs20wQ==,iv:YJ8J2FBSUwam+JeGaaMtUYnfGDA4JLCvPtmOAxox6qQ=,tag:0RGLrRVeUwlnMHben6q8ig==,type:str]
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:iSSde/Z8MpWpGg==,iv:5aJywXF60gwG4dGS3b2pP35sMHrspZ6Th+kU8HAvcWg=,tag:9cJBEkPc3yf3gk++POke8g==,type:str]
  #ENC[AES256_GCM,data:N/MSBxaSpSwmwrEvCF+2BuRYNLFw4cZn3eRfQADfmb/C8kWjuaY=,iv:jzRcSh5DHw4m9iEDGJAMqy9wHAJKH37hycq6scQb6RY=,tag:P6It9+2XJUXKxPqSX5Krbg==,type:comment]
  NAS_SERVER: ""
  NAS_PATH: ""
  NAS_CODING_PATH: ""
  #ENC[AES256_GCM,data:+4Ld2lY81EGjF2YkT4b6DfGqAwfVjkWHQtqFos+Ykp5el7E32V92bqQO77DQsv/hEUxWREIxXxQzu28esWQd5KZ2Eso=,iv:qfF6kamVRil2ddpTo3xE6jFSDRXZuNxTQLUxEO1vb7M=,tag:mbnXQQhmEZcX4BI5L+rxBg==,type:comment]
  BACKUP_R2_BUCKET: ""
  BACKUP_R2_ENDPOINT: ""
  BACKUP_R2_ACCESS_KEY_ID: ""
  BACKUP_R2_SECRET_ACCESS_KEY: ""
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:Vve8JJd/sppK1ut+Y/S9vru7+PInkaCDD90ZRgMGwXoFUpGegXQ=,iv:aFJo5xLaTL7KDyutOkueSf7ZoPlE/w0CX/squmZspnE=,tag:Zdm82vmVPjl9YmNjlPKAyQ==,type:str]
  CLAUDECODE_AUTH0_CLIENT_ID: ""
  CLAUDECODE_AUTH0_CLIENT_SECRET: ""
  CLAUDECODE_OAUTH2_COOKIE_SECRET: ""
  #ENC[AES256_GCM,data:jZ7J8I76uSATFcdY7gb8E6oTnmMv1TjVYvRxRf1WCg8ClQI8t4icRv/mpyiRTBpIrYPbdYGVrtGv+mvMwQT0eo0QXQ==,iv:9bVlpjN+bWcjB1FEoBJXOi+9WPkAlxx9UqW2NZYHMl0=,tag:vKMWrefgoVqhex4T+Vwm4w==,type:comment]
  #ENC[AES256_GCM,data:2PlAV86xW+1Eq4liNb/7TMbXoGIeyU2q4LNscHzXUu6rhx4YJucWKW8SwA81SINRNBWcJbB6hurCtYrWICY286VF8H68,iv:4y+v0jqceE09BoSwLAG1BvG7U8nCs+Lm0pCe/lO8kog=,tag:NLAxxY0rRQZqBj8em9Usqw==,type:comment]
  #ENC[AES256_GCM,data:BTuIkLm3wE5Gwr4soWSxQ/S72m/rPcyzAdXGnIg/5Y55o+POGS4I+CvLJ787K485ytDF1fvMhiRKINJr8GFQoCQbGuMX9IY=,iv:v0jVK1koTZCSgUHnnaoyphKEG6MPWnIiG+fI1PYZLFg=,tag:0tYVCX/kbYTBsXEISy2khw==,type:comment]
  TALOS_MCP_CONFIG_B64: ""
  #ENC[AES256_GCM,data:wNAYsMUt0adwNTQdcq9c0zxJ0XTJyqw/3uTEKpvEw+O3CHBXhZentcstbFnZcvrwMgkTWgRLoa95KctJep4foittJfiBOEwxjvw=,iv:UVViemLFXnJsX73wBsl0SZ6bMl8PxRsPm9A1vLNfgiM=,tag:NR/VNaTxuKa1hd3czk0EJg==,type:comment]
  #ENC[AES256_GCM,data:7gmcosTh5JfDkL2gvP7bw7k6CJwPvx74lwT2dapF0CH1HuHCqdHossRLanrO5zYdwVU/9+4y056HYZkkwuTc5rJ1zw9q2eANzg==,iv:rJw13n9vWepR+hLvT+eyvUoulVeb8g7UiSN6xfJN2xs=,tag:PV/oqLuA0yKor15hsfaZzA==,type:comment]
  #ENC[AES256_GCM,data:f3nugmNxN5FlVbU8e7WrJHyFFbu90vwBzWyz93CwlCtyLhsp5NVlRkI09bFK7QlVoG4LkN1POF3l9+TJonYaJgY4DQVDXkvhoA==,iv:4KXukZ9a2kN/vusn4f2W9LDYzp+sg0f1PY7vg2Jgy3s=,tag:NuZA/Nva+4IENU+KegyqHw==,type:comment]
  #ENC[AES256_GCM,data:MiGCgkeE75d/z1g3OT2u1cfblIv4+QwbcRdSWy30tJh/UsOXTZXGe3sqZF43c3u02eyaRgE/QK/1Umq0rbwiSss8Y3b4zWd/1Okp5Q==,iv:Qrq1gXfatWY3xdt/lZhe6FI+VZflte3jkaU1fxaaHqE=,tag:aE1zfyqasW0Uwjlul4f6Zw==,type:comment]
  #ENC[AES256_GCM,data:XfRvOYgeStdDUaezXkZTaoEICU03EoONRWclRKNnkg8BYtNWfZypeXDViu28hbRO9EEMnV/VCdr8gRJ1dZvvfhNNkaZ/BW2TyQ==,iv:K5GhKLcBsN4OQWxdBfyDacoAHHw/R6ab74O75qQGrL8=,tag:dRQJ5o8BsXE35mbyLnO1EQ==,type:comment]
  #ENC[AES256_GCM,data:Zk/UzlHOt63ZAcvqStnj9AemfnPYoLjZ5whblCmzUvjsZUv9nr4mvOXd/D9vwuAqekb5UVnFXhGD4E/DUpgnvkKkYLUzoak=,iv:bZuweu2BQNuiaKZVHMqXKalFJkY2/haOJ2dxuwiLyJQ=,tag:nwVPF0dMjaKEk9gVLMa1Xw==,type:comment]
  TALOS_MCP_SA_KEY: ""
  TALOS_MCP_OMNI_ENDPOINT: ""
  FLUX_SYNC_URL: ENC[AES256_GCM,data:sdq6a6JoWBVkbnwkJ+em3XOI7PJTw+M63KQk0Rv4QV7Ltt6HzXFJ8LOXTFFi2DU=,iv:+K7QL+hiXfVAcwS4drjM310O3ylBIc/Pc3lApKC7JcA=,tag:WOmbaPFLwdOdpcKrp2SOzQ==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:PWQweVsZNFVIAGITzIdJRU2fftps4tWLkpsxd2R38xbev+fvMdBG23b/Y2f7seC+ACwEywfTDJHSWyczCntYcfgIRpKCMZ4PuiDRJH9xHu3FTVUUr9zZDCtTUFmIekJDfzYwxW89iXlxzCj/5IpvGtECjGC3KzeVq7zfxKFn5YLdTutNc7Cz6fRyYiEwnljs+yBp6EphxaKMsNKesxodAaOTHZlU8O7JhbnCxzhymLOL3eez,iv:x4YkrEU7Mh9irrJRILRwnwPuAAysLN8SYGR7mgCOZ+Y=,tag:9s4So58bRRf6wmq5fwYg1w==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rH6EFGiFWj6OuZY4gWFVSOokBCvazTDve1YUXFtw4eD6Uxz5,iv:JmflvjsMbTl2zfji5+1nri63TyLg3tu4bGFSxbZwfvU=,tag:QMDCi3LM2ahxpjgX3u0A5Q==,type:str]
  GITHUB_WEBHOOK_TOKEN: ""
  POSTGRES_PASSWORD: ""
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_CHANNEL_SECRET: ""
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ""
  DATABASE_URL: ""
  SYNOPHOTO_AUTH0_DOMAIN: ""
  SYNOPHOTO_AUTH0_CLIENT_ID: ""
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ""
  SYNOPHOTO_ALLOWED_EMAILS: ""
  SYNOPHOTO_FLASK_SECRET_KEY: ""
  SYNOPHOTO_NAS_USERNAME: ""
  SYNOPHOTO_NAS_PASSWORD: ""
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ""
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ""
  DAILY_CHECK_SMTP_HOST: ENC[AES256_GCM,data:6fb4ABq9ltPKBl5ZhSI=,iv:1q7IOBETaLvy9UOWUV7t892qfTDF+HxbujYzrz3P89A=,tag:4V7TabmiBPLlsRqd9TOpJg==,type:str]
  DAILY_CHECK_SMTP_PORT: ENC[AES256_GCM,data:sKAe,iv:PTpvSbQkz9/5paICgGh0hanjZxVUtmAsaMjiwgRaDfQ=,tag:8ipATmcs65Xlgsh/Q8U+rA==,type:str]
  DAILY_CHECK_SMTP_USERNAME: ""
  DAILY_CHECK_SMTP_PASSWORD: ""
  DAILY_CHECK_SMTP_FROM: ""
  DAILY_CHECK_NOTIFY_EMAIL_TO: ""
  DAILY_CHECK_HEALTHCHECKS_PING_URL: ""
  DAILY_CHECK_ENDPOINTS: ""
sops:
  age:
    - recipient: age1ef2ue7kfz0pu4pj7q59ekn4nvk6np3pvhlh8dh7s32r2qsfs5u4snflxra
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOTZ1Sk1nbklEODBiZ2xL
        MG9EYlhNN0N2VkVQRllieWEvdDNPbW80c2kwCnZmWmpwdU94dDl1TU9jcEtGYXVy
        SXo2M0NLempNVnlRUmprQU8rK3VqbW8KLS0tIDAvbDRWdHlLSUNaYUZkbXNUMGFM
        eG1TbU5BY0xKbXI0bnlsMHY4SmpTMGcK09tkElVhO04sCRlQkJRuV/ytL4prrMfr
        zCOin0Zzv8WnSLAIfcvxsym+otlyGlrC1qHWSltkYzCzh0L4miCHzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-11T06:00:48Z"
  mac: ENC[AES256_GCM,data:lKw+CKDNEOk7XBmn+LAHwXG1GQDarCGlLnT44tD1Ze7oXy9iYha9gMmehF8FztekiYu0FHju5sahdHMetpvO7uEdIdyyE+9tM8C9Lc9wrFHwMEJ0PkCOOZcgft0GXn404nUN8vqODcIIJfxFb7eU24HPocLOOV8o7/pA/eKW9Z8=,iv:Bkdrlxs8ynQwEgWXxDJ0HJWZAKFmvTo0MG/uUaaQ2lI=,tag:o9uf5hqT3ZpQTPhOGJ0h8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
