apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:jgiD2CjJ21M=,iv:U6sAvEOLO/CY+S9OXnhIjVszKKNJozsTUnhY+udzSTY=,tag:hZGQgPRSh8wV3Zw9e5ahWg==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:tRhrz9BrHch8D0U=,iv:ot9jrfiz9aRHNTus+qPbX+g7HfZAK9dNHEHnB2rYZf8=,tag:qn7fCraxga7VRPQMqKLLOQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:sJ1vDODr1JmYNw==,iv:FPu3xq9hb7KEgD7+fD5yx9RyosSmumJERX74D1mRpME=,tag:rsmwkpMnBb5wBJihdzrUlg==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:pvoyoFNvcrxM+6A932iL9urNB3/7xr/KdEUh5soGyScGLKyAr1v6BSsi6lC0ii2qHYr2MHQ=,iv:vpYQdAN/iLzAMj8NPOevREo8KOvhVtdZG2rHvIPtQUs=,tag:geya+w/ulY895OSGhtdlIQ==,type:str]
  #ENC[AES256_GCM,data:0X+P/DBT+d91lXdqnCdX7JIV5AQShim+9mjU+xzMTlSF47KS8YE4XbhxpjKc7VRX2U6rWRZB3vEdbA7qHoFl6684D0vzZ3LND4dIfQ==,iv:PTC3dMIyfA1Fy8DkBoQj9Ss1Cvmuj0qche9CaBhzxB8=,tag:tYoyAQ11kaN2zkpFz8pBTg==,type:comment]
  #ENC[AES256_GCM,data:cVjpS4GF0YqWJ3x7+HiS9OZJKLT1cGxGxnTTAB1uhyyTi9914RXT3lCGjAI0N0B/O2PDl47Rcpa4A/aq/hD6cLHZK9hHhJ12,iv:zFSbxM8eQyJ45Q3ru8t2yMtCE57yOLyBw93rU+Ka3uY=,tag:8vShGIY/VeNYeEx4ARjwKQ==,type:comment]
  #ENC[AES256_GCM,data:t+Vq02Ogzor/PC1FJIGYffnLBe8L+kH2TWOw0psR5CjrmmISUN3oarSCp9GqcCvzmr138PC57Y2VAKbOlMOr/aQz2TTK3kSNZCJ6Xw==,iv:69DVM/OhWG1qOwbNmOGrCWgc1OPMeJbmJVIhnRnOSQo=,tag:tHfHQzyHa9atj6htKC8xDw==,type:comment]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:4LeyLMewmlRoiA==,iv:Hu0IV6e5wNNO7hqJX8G9H7BDV5jyou28i3U62UXZu84=,tag:JhO3+qCoT2iiC5624cy0EA==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:zvquvdr//BEpNQ==,iv:PzaFC3oVaWzjUvbfp0IV0yo67JmK7pIz9i3YsWloXUg=,tag:MEqPcTAwSE1CdX1FVKjNtw==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:D6/pU5JM/snq8A==,iv:qJIXQnWj5d/f1EPN7b2CAqFwv8EB37ihFIToEMQwzh0=,tag:hHoVugHEKiZm3oKm3pFT5Q==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ENC[AES256_GCM,data:myxiPxNyqaSzOA==,iv:5FDVfLFhZmlwODIBJff5PqnPBx3mxLj+weK528lgx0w=,tag:/5lnmywPCDaewbJmiFktGw==,type:str]
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:2EWa2QlW9Kt04Q==,iv:RP1NyND6giXdpFeadK2Y4GeXWf8BWufhWpH9FwEW5Ak=,tag:6Uo7M1FRsVeSfvRJNvLA6A==,type:str]
  #ENC[AES256_GCM,data:n2h0R1vediKbuf+O5AMbvW8OHweVRMPdKbuCeVDl7pg2nk94z4E=,iv:t+H0sjwcVVKdYf0JzZ8HqIqwtXPdvIIKkR3l9SV7VTM=,tag:j2MbisVlzlrpAYIFjsNtIQ==,type:comment]
  NAS_SERVER: ""
  NAS_PATH: ""
  NAS_CODING_PATH: ""
  #ENC[AES256_GCM,data:9+L9D4V1hLGyymLMVsRTNeWNRW1fw+xHTa3e7qqUOIY7rbvgj7P6E1EU1+s5OKEyg6BeQUfgYfBb1JauJ5ZkxxJIQjw=,iv:oo8BHRCuxZRjld/ynZnp08OcjOlmnNW6pDWmITKAvRs=,tag:3+h3OpLiIDgj4/zIu55W0g==,type:comment]
  BACKUP_R2_BUCKET: ""
  BACKUP_R2_ENDPOINT: ""
  BACKUP_R2_ACCESS_KEY_ID: ""
  BACKUP_R2_SECRET_ACCESS_KEY: ""
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:M0hpbD6F3mdY1QEIdPKTIibMpPlBgjZCfN6VtpXPnoFYxvqwgTU=,iv:M4KQ/AInW9PKPjVPmq3hD/9hnFZvSM1zy2wVVrvHdno=,tag:NUiMfm0nqpbXQmiWrmVKYg==,type:str]
  CLAUDECODE_AUTH0_CLIENT_ID: ""
  CLAUDECODE_AUTH0_CLIENT_SECRET: ""
  CLAUDECODE_OAUTH2_COOKIE_SECRET: ""
  #ENC[AES256_GCM,data:tH0Cvf/oOkMh5Bxl5TpDPx/Ek+2/puXH9uc7UPsaMr5AfIwtiAqY168IBcFAd7VOfpXgt3yUfZO2JvIbnbnXEsf4nA==,iv:ihgBK9He+rWGuuuE2EatMJ5SDODw5UUS+ik9dqm4f3E=,tag:yIOjiGU2sxyWMKe7BzIwbg==,type:comment]
  #ENC[AES256_GCM,data:ZhMuFcmIl+4lSyCkw35Q+d6B7fN2JuyFY0HrCo9dOFh1ipPDN5S9Ea6NcLN4YOBXE871Sdkxo+sdoxsO98Gqwom+QBFj,iv:6NfQD4POASEerU9nrxUsrJC8uxGwhM3CWRkBHvwcMVs=,tag:CczKcyA4TcMROEuFEumesg==,type:comment]
  #ENC[AES256_GCM,data:Zx8oyj80UrnWvMkD3fwJmkh9DTuDw+Up2q9VNj/3AeZpisfh2VlJCwQK12Y7MXpEe5RDAwRfoWzjRkBLIBmNkPVLlowCWzM=,iv:TNXTo80V5mtZr3ryGL0SjheRD25rk6S88yAEWgARYjk=,tag:LoMrCrr8TFceIaKByLejRA==,type:comment]
  TALOS_MCP_CONFIG_B64: ""
  #ENC[AES256_GCM,data:Or4WbfP5YDBhl99Jxmc7NkUshT7U2/ZYQhWQoNo7DfBAyYnWWV+csuitV03mtCijaXO9X2Tds9bSfaf6GVT4VMdhJr6BcgbQwGg=,iv:zezvkQTWpLnEfGgXFJU1qCJS7MmmYBarVnokGMXSAQE=,tag:jnkxifcErg+Hl8pPSjYxBA==,type:comment]
  #ENC[AES256_GCM,data:la64CopJBl4jWteQjLzo7ql1C+REYHL1o4yuaufwCAuHmitG/YD3Yb/45N1N/tVEn3ah3pNuJGCB04fJ3lqpn/0/XiW3ZlsbtQ==,iv:6RE6wH8m2jZHA5fy1iKkwuFGYLfJDI2xqIe98H5vBYg=,tag:23A7Qy0qCP8/hh4L8nJQkw==,type:comment]
  #ENC[AES256_GCM,data:xjwVMfoPx+Fc+CQ6kVhPfPStrN0MkMS3gdNSM3LXVtAuUMeAxztuYBkS5bQFyV6GOIcMA1DelZDanDIEV6CUI5GcqUQ5S7pAzQ==,iv:0KUSoqqrtO+ZR6+MwPHVpQ5E9UATSyerPqBLwzHCAuk=,tag:gyhHNChlBVR9iMa+Sd5EQQ==,type:comment]
  #ENC[AES256_GCM,data:0FJkLrAl99K3c8F3ytxkXYYdeG6/ZffIdzaFU2GASABbseRVAHVyQX1L7S/LcOcrxFOtYpV2e3uPKmo3sUhOSnCNby5+Imeck9YrdQ==,iv:XQAkVXiJXN4Jd6QHKGGPMid0/bjVkSvpr/CVrefkexk=,tag:ir/WrPMEiKSJo3yWs2M3Gw==,type:comment]
  #ENC[AES256_GCM,data:Kk+AzJaqgTJeHPfSkJhV0SLCmOPD57A41x7Q70h9bsN3FYuyLde5HMXeOGBM2gjoTOqFqdVgUpDhMpbdxIMTDWecr5YvLgvnzw==,iv:8A8+iFv28NZzwl4Uqp6+Kd9jsvakBB7PprNshcz2iZ4=,tag:mFI/4l5ogXjo9ksDkAVPxg==,type:comment]
  #ENC[AES256_GCM,data:EsdGzVkbZ24wZyj6k1OGrFqAasPsQAywixBJsIloGhbAhnm6k/wceRnJAI+61uk1djT74VzSzKsF4rAUvaUSnsdlND8OBoo=,iv:JZa/u2EIbVM5Pd293fCv+5xORZIltkZ4s4uk2JPU0MI=,tag:7uobz7Ct2KfIXxlMh8klVQ==,type:comment]
  TALOS_MCP_SA_KEY: ""
  TALOS_MCP_OMNI_ENDPOINT: ""
  FLUX_SYNC_URL: ENC[AES256_GCM,data:uEz1+mpUyFbpzPYevtHtXgaK/MhlykTe2d0R4qhQ9Cu3Jy85xLFCAhKhI4Y1D6Y=,iv:NG5yU+i0JH+wek2Fqat7wVcjTDIcgi4tQ6QvoWpEbqY=,tag:WjkncUVQB9l+54oQc+djdw==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:3ACQI9KHSeDp1wR6I19hQR6K6d/HGqcr37U7DjPzv3vXHE6f2dSS5hchnXf0+giDd1k6rYIFngHO2yVXZzLZVK82Ym4DPENHBAjR6j6ohcGnX90ecLp19MuXRSQhwGs5yBwWNDa2zk2rGaxk++rtSKi7Z8nY1c7gF5KQEe/pBH1WSzAa60uJMEXXmETCsIX84lJNuZhVkbP+UsWRrhnZJYE22I5RRdVSzXKRufUGnSfCzmBx,iv:qiEQfhKc3I24lglDOOOQKPhLxe7sjppzGhIZPGT4RrA=,tag:wpQZFk3gkw1Nysvlhlktyg==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:E8ZYcmUq1zz2ZYWeVXU3YZoZMILcwoAPN3RNUryOeXSBAw64,iv:R3w4K+obkVBjW4SOty95fACTiGDM2TFmUqfH3KqWZOI=,tag:yo02gTh79mG7B68WR0/UkA==,type:str]
  GITHUB_WEBHOOK_TOKEN: ""
  POSTGRES_PASSWORD: ""
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_CHANNEL_SECRET: ""
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ""
  DATABASE_URL: ""
  SYNOPHOTO_AUTH0_DOMAIN: ""
  SYNOPHOTO_AUTH0_CLIENT_ID: ""
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ""
  SYNOPHOTO_ALLOWED_EMAILS: ""
  SYNOPHOTO_FLASK_SECRET_KEY: ""
  SYNOPHOTO_NAS_USERNAME: ""
  SYNOPHOTO_NAS_PASSWORD: ""
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ""
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ""
  DAILY_CHECK_SMTP_HOST: ENC[AES256_GCM,data:bix4ahc+q+hCcJtBp4Y=,iv:DDOfrJa1JzLREWw7PfsXTDfVN5q/6zc2DUTYcRSw47c=,tag:NgeXNI0JpiYy1gfcUdlE4A==,type:str]
  DAILY_CHECK_SMTP_PORT: ENC[AES256_GCM,data:hGSb,iv:vpHUBsq2jEHO0RVU0+YW5m3obwZLkQbUPGVBAb0FTYk=,tag:X5zHNxoUHLID3Xw+rUE1Sw==,type:str]
  DAILY_CHECK_SMTP_USERNAME: ""
  DAILY_CHECK_SMTP_PASSWORD: ""
  DAILY_CHECK_SMTP_FROM: ""
  DAILY_CHECK_NOTIFY_EMAIL_TO: ""
  DAILY_CHECK_HEALTHCHECKS_PING_URL: ""
  DAILY_CHECK_ENDPOINTS: ""
sops:
  age:
    - recipient: age1ef2ue7kfz0pu4pj7q59ekn4nvk6np3pvhlh8dh7s32r2qsfs5u4snflxra
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVngwMlFva0RIcHRFTG53
        blhhaDJwVXVCbTFFSzJyVytvM2Q2OEFXMWxRCndjVkRHWC9RdUpNTk45RXA0NE1u
        a045MzFzUnI3WHFEVGtzZnZYUVJ1aHcKLS0tIHpkMS9CNUZIS2tNdkZEQ0VIQ05F
        Z0NYSDBFOFZmemVORVNjMS94a0MzdzAKzNpxq1/pRXpBy+off0/QHMjmDRvakWBP
        3jJElqA57ZzHBkitkiMIEhOHvy/NExJ4FtWfE/gBx1Nvzm3/Bx5oSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-11T10:47:19Z"
  mac: ENC[AES256_GCM,data:GVhXJK9lCMd5L9aG+E+N1zPwGo8kY6+6rFHZbqohrXNSDzDN5uMezxX5klp963EyiF5eS1fVSvZJoXNFpZTfREYhrCN65yPyd/TXGz/iXWmZXB9SHZLsRAftWn5Y+pVfotOzb4S5S3Q+c57gK5suuyCjtX7SleBxGseZ5/4uWAg=,iv:keKLRGpG4G6xgPnSjHoYGiRCB+qlSL+EJ+aB46JAdaU=,tag:dbXnl3JOu+NZ4NaQMkNqWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
