apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:0ErhV4ny18c=,iv:ID4jh8G+UpAP/oT4M/vGpBO7usBoJtAY22XHjqC1DvQ=,tag:NpqSGUtfXCEHZuihhMwUUA==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:0yrZKCj5I/smVKo=,iv:8ZAXzQZPiS9UAIkn1ijk+O8BkUjHPBu+T+H7s0mkRc8=,tag:oQfY4MfH/KgDnKjWzsPUjw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:OB6T243DhGWbbA==,iv:fszm6F87xCThENIQOHKn1nQt06yRsBhRE6Z1qWXsK7I=,tag:HRyXc/hhns8KoPTRYxlj8g==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:7WWnpIuqqfnrulVg8JVkZb/tYiYjbjEmy3rc0zyXDEOKfWv1volAazQ97IFCOPcfBqfX0TQ=,iv:s1xHcJtNJTsJXuKV3EoSzqINEzHtzcHF8cuqShzBeik=,tag:BS+/Gway5ZKmIGkIA+ya2g==,type:str]
  #ENC[AES256_GCM,data:H1LpXA8vXI+izXgffRboH54SgOuUGd0pis8SKYR5uTnfOB50oO7YhFLbqYwFReqMZnTC4GMrWTO/cYqlY9THHlrWGoObEBwDFo/W+Q==,iv:Py1xWm4I0QlU2tBbMLKMntDm6myH6w7PTYQ1Rt4qMfI=,tag:kOhO+nzcHhgLL94oOMC/GA==,type:comment]
  #ENC[AES256_GCM,data:gY4yQN/FXhnv9UBhP4PIOLBJp/SuZjQNOylifnk4QzUFZOQ4vIckMYd/5ixfLxyoF7HfFnFP1mQahh3TJFXmTf8TYWPFwpey,iv:zvIuLx/HzCz+4/9D5uH+6Sgx4z6IIWzcaJPxqNu8zNc=,tag:eMBFrWKCXFaTYzxJRfEbXQ==,type:comment]
  #ENC[AES256_GCM,data:PXRRJvqo+h1DK19tr1/PO4q4dMyU8pQVlmHy0oMrYYwTlFHNjFp/PezOJnOAduhiS/BwyifIBg9m1Ta01aaOzRJD4R+xzvQZFbwMYA==,iv:ghbvOQC17FKPYqn2+HQ2nGto3IWnvo76Yf9zdYL8QN0=,tag:q+x5p/QMHgqx4NSgb/Y7Lg==,type:comment]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:QwiomNOcXZ/tfQ==,iv:kmAKXB4eReu9xmJdFnITENcRMjxdJkdqp+rClpUXbrA=,tag:67cbwn1ECX0jSgDDtIoQOw==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:+1et5f429KLDxw==,iv:lLzLj99E60VuuFNzCkYXMoCblS0+SXJiVFyVB14cIRk=,tag:m9eSxyzvZR14ZR2Gt7A0+g==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:qj7sxvhGEhO/5A==,iv:EwKFptWuQW1Ko8TLn6yfIcHIZXOYb44I2fTEbcX/la4=,tag:4M+hDhW8VS2NmVniprOXmQ==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ENC[AES256_GCM,data:vKODGyjbq1+Cbg==,iv:52CMwxZfVO7WAviifT0D3UhW5Jc9h0amfkoMrTmANR0=,tag:X1esTOXQxptHSl2vAhX6mA==,type:str]
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:iLDKZlWQ/sF+CQ==,iv:t3t/IhO5HqiDglFwK3huaifwLofIZdAfivqbbyKbZ6M=,tag:iW2+BUbVJKgVUa/m9Iw1Hw==,type:str]
  #ENC[AES256_GCM,data:mecDOHAb1IDX2X5JC+Hl8boRKyGC8NqT9chmQlma0aqbfYdzbSjTw+x4+0LXTrwaI7U9F7ijLJfxpzK/mwoQh3nuxIBwolUE,iv:rHMdW2JviBxEAjnRsONxVwdIibfNUhrHRoMDRCb3MA0=,tag:kvLS6w0+qDWNo1HfRkUQYw==,type:comment]
  #ENC[AES256_GCM,data:/Jpcqy9ywn+NJLQhejEq7HUCulktbF4bDTm4xDgy3gK9uvfZO9glinhh0IpZqH2Hf6xx8XzY66+TKSkvvIQo0GKdxFfpOg==,iv:bTxbfnY2BA7XGkVcO3X5e6vmu+fRt8h8Qa6jbhrF54Y=,tag:n6mGVWcn4vSPfHNH1Fl3qg==,type:comment]
  #ENC[AES256_GCM,data:QFsXpOZYob83Jp9jcRZZk3uNDtoBeAcGwevnuFo0r8rmLKgL3WXtmv1BC2pIiJYCfMTkbSVaRZIjDdE9ZKPltsWfhvNIl373aA==,iv:6yYrSsVKwq9F92PFMZWf6jPN7mBSjnx2Q2VYAzupB2E=,tag:OeRuz0/tWRDmZuVZYwvUUw==,type:comment]
  #ENC[AES256_GCM,data:qaHSxTKEwo/LgVo31Absx2sLsJXxRzCEMi8FL476qvVaYDiblWa8CgdATfTxIrj5xlywFtJpUdgJsfMn1vaQ7o21L/taryX5C2A=,iv:v/CE2+7zfYa5gCPSWkVKwEe5JVOXthdGVILvSb7bFSc=,tag:L1hRDJyRleTKr6EbvgeVmQ==,type:comment]
  #ENC[AES256_GCM,data:sESSCihI0eOrTyDFgnHs6Viefw3ovYFDuzHxUHqvnNS9KFKHcRKewnVdZSVOVTFbhITaZDSLIXqX,iv:1pRBDsGOV9kKo9Y+8kydinn5U6edLU1ndLJZy9cJ3DU=,tag:vLJc5+URmTjM53JcpBnLEw==,type:comment]
  #ENC[AES256_GCM,data:pBCqy+N3KyXoVbbj9R9N852exY8mFxaX22ZKh8bpnff10viOaYLaQ3ZHeviXsZDD/Hm6M6pj0HKkX3ite6atCUfyraO9KvQ=,iv:N02Dtqk+duc81ZuUvbrY1B1RTZMZAz1Eic84A0iMPJQ=,tag:I3ukyTqr6jXxQzIaXH7QVQ==,type:comment]
  #ENC[AES256_GCM,data:7kLX4rFlGgO20g6WR1xEQ/OmJXpWpHBBAbHl5ZcVzy0u+SSB0VdfIa3E7ox5ddeD57EVacGGI3dgWyP1aonuOmdTpKO25W8=,iv:bCikv81m18R3Of8h4RWmTiM7CLq61Q2M9cKNli/3DN4=,tag:gd+RJsdrtZjJBWTiIVES6A==,type:comment]
  ENVOY_EXTERNAL_SERVICE_TYPE: ENC[AES256_GCM,data:qIYgk1G6QXqilii9,iv:lAY0yiZ3EvECQRpoJ0WT7z0qdCwXU//7v0wTqor+6Jc=,tag:KprMAxR99amZz6eKgTOq2A==,type:str]
  LAN_SHARING_KEY: ENC[AES256_GCM,data:mGCP,iv:aHAwtnm0zr9mtL27Jk5hFYDNY0w+rp71isNU5DogBYg=,tag:I04HlNdWPMWA4+au1dpVgg==,type:str]
  LAN_SHARING_CROSS_NAMESPACE: ENC[AES256_GCM,data:+IUcnYsa3TysTMPV,iv:o0pFqxXO+EE/Q0uVen/x8hyISyAfKDduHo3avLmoWhI=,tag:rTkwN4q1R95yDHmpK2uF7Q==,type:str]
  LB_POOL_BLOCKS: ENC[AES256_GCM,data:VrNyE4LSbB9BFX8ICdYdSUYsk2ggIEqB1mjQgUTr0ZntxiuDhoV0Topdf9DLZHjBsgMo6lSdBtwokoHDIl2edKeLJhwy8zPIS51O8VCSDoB1E4A0jtnq,iv:ohOV5eiGNOw7M3++ZO48vdV+eB9xyAmC8EhOM96Tr8Y=,tag:8EJDmM/et2Ikg8wED5F3+A==,type:str]
  MARIADB_LB_IP: ""
  OMNI_UDP_LB_IP: ""
  #ENC[AES256_GCM,data:O8IUjXY6hRuEjqz5vDhdcgVcIGobq4PZuz5rzmKMs9z9+piH6BN1A0jOeTjaSTNE6hCBJkdst84fnO9Y2w==,iv:ntvJ/fT6t4XOtiAdlPDmNE2imsEK022U973k1Bvpgqs=,tag:d9OXgR7dv46GCgMl/38yUw==,type:comment]
  #ENC[AES256_GCM,data:dMFv+EzaoXiSOE2kAF6yTLCcZVmPYT/SDsKBDVASHgM5smV90ldSRsqU1As1UqSx5rPpgpZTsU9vhgp14ZHqzHY=,iv:d3ZrLcYwzhTl30gcH+yMPFBmn3nWtr15ewEeD/DtB6k=,tag:7+U/WswS7Qsgetl0mJK6OA==,type:comment]
  DEFAULT_STORAGE_CLASS: ENC[AES256_GCM,data:eItWSzD7YeK7Tg==,iv:7SGYM7r3louI6DHwEp0/t46n1GRnmELzdntNYW+BgLU=,tag:JncO6W/Qu5yQof5+ni+Yrg==,type:str]
  DB_STORAGE_CLASS: ENC[AES256_GCM,data:tV7ioZ3IXmSgtQ==,iv:EMkLOmps8BLqJRvIym5FHkKpwnm/wAslZ5Ot8r7+5hk=,tag:+pZ6CBbc37MghxK0g2bqSw==,type:str]
  LOCAL_PATH_IS_DEFAULT: ENC[AES256_GCM,data:eWOTGw==,iv:vAv/L3TDoYnp0ttRpnnX/appuLkOqiAJfX6e72GnZd8=,tag:5uuPavXF5At5CMvhNtv2/g==,type:str]
  #ENC[AES256_GCM,data:v/k68ugQCACIpJaEL8Et19QSSCn/M42fvcw7RmNUmMYk1h0sOCg=,iv:kis0HpzoXFxujTaWaCIkvSq7M7owZf+xcuN2X45M1Rc=,tag:lKtXt9k9FsXU4BZIOsXPGg==,type:comment]
  NAS_SERVER: ""
  NAS_PATH: ""
  NAS_CODING_PATH: ""
  #ENC[AES256_GCM,data:HKfuR6nwiCFmIDPTW3YmUSzJlclZWhq88RVCsAsClSjcTbAWFmDnRhRcBmxxq+3pZX3NIf9N0Qi6zHByNHL//LrNN1Y=,iv:arevQtQTbmOvVrjf0EslY+bbZhiz0WHw1r9p8CpFTBo=,tag:COPvxfPCqRaHVlbTUTO3fw==,type:comment]
  BACKUP_R2_BUCKET: ""
  BACKUP_R2_ENDPOINT: ""
  BACKUP_R2_ACCESS_KEY_ID: ""
  BACKUP_R2_SECRET_ACCESS_KEY: ""
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:+zTPpHaZULLAIugo18nZ91JtRRkwnIojZAt73MA6WWF52763jqg=,iv:jcblwtnEKwcvaAEY0ozoOjkWDUScKIdULKjp5o/VfUo=,tag:EHG8qz76NEKNE23ahG6B0w==,type:str]
  CLAUDECODE_AUTH0_CLIENT_ID: ""
  CLAUDECODE_AUTH0_CLIENT_SECRET: ""
  CLAUDECODE_OAUTH2_COOKIE_SECRET: ""
  #ENC[AES256_GCM,data:HwsjAK3kJSmLavap85tD84BPFrymKLPSQ9mdn1AfEByEfSnLTzVQVrK6L7kcHzIaCzWwIgpmeo6UD3awwgll9rsn2g==,iv:+UVDwpbRfn07w2haWJUHWv6L/SfiPj22KQmAVT5DuOU=,tag:zBwuZ4I9pqJiuexD4+5pzg==,type:comment]
  #ENC[AES256_GCM,data:Q1HmjuWE2/3eSFUP8YjbWnRNQ8KG0T9I9TaQLSOV++IQF5JrStoHBD0+/HdXPIOE/lwbTUeRk/bUxCarn4vxgyIzUJjc,iv:YTe9xl3fu6zF6hUcnkHNCY5z03mTnScm4s0GEIj+T/A=,tag:06vVBbAcvqe/veMX60bqsA==,type:comment]
  #ENC[AES256_GCM,data:nXo5Aom1CT8ZK0nz12qI4Vz0sVFdAMtyE2FBjlXZyMJ6xMRQe0kI3ctjeOlZjFONOyC3pKd+ho0pp2jk1myX7unLYwk10Yw=,iv:qan4Ss0zRYf16Y77lJioASsr5PXsUqSYXDu5tYj2iAg=,tag:fGGPx8A8wUGH4WKK5a754w==,type:comment]
  TALOS_MCP_CONFIG_B64: ""
  #ENC[AES256_GCM,data:v96MYfu8zzEi0kkUKP8swoeGnp84ZlwCxDkymKxcGSWVYpeSTyrRdBkYRU55YqSu4te+qVEEfmIkLMt1R1uxlnw+fNePHG0a0HQ=,iv:ESp3DmhqG37tOYE8IrWqCNt+tHRD0oec5+3Yx+aUu7c=,tag:ngZCHW/kimutQnA/vIiNTA==,type:comment]
  #ENC[AES256_GCM,data:g89hSGF/12gcAMru2nU0NZ6Wg+x2GV0YGb9WYksBd9zvsEQp125vfPbhY62n/Pj5lv102tuGF0KZ2izwUf6Ln9cYhVp0dwj7ZQ==,iv:QI5M2xO/ilLVx+fBLRcaEo/cMHyqwGYLYMBNxLaA4vo=,tag:tLWs0J4841uMauz20+9Mzg==,type:comment]
  #ENC[AES256_GCM,data:T9B4moCvdvnRVYkUg6xB5LkH58SR1fPqHNadyc4r7VoS0gx3cah+SDvGFwcNtsYBD9UxjZhBoCJ0Hxg7bqWywruIRt+nkxrUgw==,iv:AsDynxc5WV4b3SodmDE+JNj15SNH69mIFR41o/wn+cg=,tag:YSIRWgHGMYKcCAaSCvc4dA==,type:comment]
  #ENC[AES256_GCM,data:yF24D7KmhFdsKVrR/QcVBbEzpCd5GJykDBBxDw0m08xxV4mpXRNQlx34fDiclJMWYk+wYcyawWXTR3h6dkUdNfQaIjy1/+KfwcPGwQ==,iv:M68rESF+wrzx+syVgETcD4nrDx4CVUqPuE9IyVvESIE=,tag:+XzPwmtnsD4cWidnffs+Kw==,type:comment]
  #ENC[AES256_GCM,data:6TUQl/bmKOIP4OpFOVvi2WMCoKs6+717DOo4KFsDSGiVo5HhP9BHk0eE3kga2oAif+1D1BHoaTaihJQuuuVqbRluCWXGForM6g==,iv:d1dpOpSnEU0ymh9qL0xkdKGHyeyHOh2ZbwDSxsIx7rU=,tag:sQzcKja9PbofVnYqzQeR2A==,type:comment]
  #ENC[AES256_GCM,data:bnn4+fCJqAZq+UeARBkoHuraIUxHCzcx5915TqYX0YpPdiP4Hi6srkkuT+guhhvjYj7PEGZo8o34SjnnPBSCRq0IqE6ZBcc=,iv:CA6pJR1rZODM5mNM1IGVtSLDMHv303OokSJvIOfRmTo=,tag:Z6bO7nkUmv/B34k/WbnIhg==,type:comment]
  TALOS_MCP_SA_KEY: ""
  TALOS_MCP_OMNI_ENDPOINT: ""
  FLUX_SYNC_URL: ENC[AES256_GCM,data:ITCzkFFr0dxAbU2ltbxKOe/u5okNNIocSaRKpp9Lw+QtonSwsotNHSbV/XEOoNI=,iv:hpaPqVkGUXvhuaVCXO92h133nooEd3mJ+Xgh/FhK4Go=,tag:A8TQb0Nmnw02oEWbFNfKyA==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:zODt76N5Vcjyb8jbRmB7qGaKthQSI/S27UdyMOPC1shhqpWc7Ng2PBkljvoYupd/pv+oARrKuqAvvPh52E+RdTWoQMvXs5V0NrF610HZUUsmGBlTxm37w9coBdk1QC6ydpy7L//w6LLYg2ef0YoysLidkEeVatEvQKJEl1Fp/OK7ib+iMpS0EHsGl07pkPh+EgBXUpO7cQCsY365CcAoOsLW/EHO9K1deXHMLgyPgwbnvZ6S,iv:2uy5VHcNuo2yOy6KJ83mI+cnyPW1ruCFeOpR8DTPSpQ=,tag:aZExQQxM48P6L9FypQqybQ==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:K7QTxD0m2HiqNiS7N1E3kDvsmFkZKSCyqEtVi25BmMd9tPFN,iv:8FjAseb5ReN4c+YWGnAODwSuMEb5uVDY84MYXnwPRkY=,tag:FxPGWuExeKYsf4GsMUpC5Q==,type:str]
  GITHUB_WEBHOOK_TOKEN: ""
  POSTGRES_PASSWORD: ""
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_CHANNEL_SECRET: ""
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ""
  DATABASE_URL: ""
  SYNOPHOTO_AUTH0_DOMAIN: ""
  SYNOPHOTO_AUTH0_CLIENT_ID: ""
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ""
  SYNOPHOTO_ALLOWED_EMAILS: ""
  SYNOPHOTO_FLASK_SECRET_KEY: ""
  SYNOPHOTO_NAS_USERNAME: ""
  SYNOPHOTO_NAS_PASSWORD: ""
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ""
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ""
  DAILY_CHECK_SMTP_HOST: ENC[AES256_GCM,data:hvXqvEHt92XS/EhlWms=,iv:ZTjvGyN9sBwwvBLrnW2DP1MX9K2vxgeU76WyGhVbWyU=,tag:5fhyRkTuTsye/MhUCsjLKg==,type:str]
  DAILY_CHECK_SMTP_PORT: ENC[AES256_GCM,data:+mLw,iv:uSMcQzJGxPyFGDLmCUEqKuwPKuubuznYcUsFDGH/gAc=,tag:WM6/+Xu4sVZv9z1Q6/5nhA==,type:str]
  DAILY_CHECK_SMTP_USERNAME: ""
  DAILY_CHECK_SMTP_PASSWORD: ""
  DAILY_CHECK_SMTP_FROM: ""
  DAILY_CHECK_NOTIFY_EMAIL_TO: ""
  DAILY_CHECK_HEALTHCHECKS_PING_URL: ""
  DAILY_CHECK_ENDPOINTS: ""
sops:
  age:
    - recipient: age1ef2ue7kfz0pu4pj7q59ekn4nvk6np3pvhlh8dh7s32r2qsfs5u4snflxra
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK0RsWjU3ak5kejhBTnBW
        V0JwdCtrNGlTcUpwb3dJMk1oYk5MWEdCMFdrCldoRTk5YmFNbHVUWjRXZUtwcTkv
        TUFwTEI0TW4yR0xPVE5BZ05GWmNzNDgKLS0tIEpsdk53eVYrSFRsVjlVSUx4WCtq
        dDBKTjRMQWQ4UW45TW1WakJTUzZLaEEKPl6x7rGVhA4TbKia7qh2GTJOORoWSbdu
        UrKD/T6YGf/TeCHqwDwAIExU8lBoNErHg//VZMkHSa7HiNgL3K/Qjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-12T01:55:09Z"
  mac: ENC[AES256_GCM,data:98wuO8mKqTx6Hb4Gk4IfXnykWiDe0Wrr22E3PdhCOYYYgZGSOoAlfiXbecoB6JQ8R9Ncst5bzYrPYReFPLWbLUcj4RZGZ+jSG3fJP8tA+dMglIJMpWxWG0Eqe7T1AgacSDBMoGyQGoxlEJQSqTnbaIVPhmZUP5/y8DroK24xOKM=,iv:Tnw2v29BlKt7bQzLeBMjSDTybkCau4MnC2xMBYR9PnA=,tag:UE3zNTy5mXCjvpxhE8cANA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
